server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true # 브라우저에서 해당 쿠키에 대한 JavaScript 접근을 제한합니다.
        secure: true # 쿠키가 HTTPS로 암호화된 연결에서만 쿠키가 전송됩니다.
      timeout: 3600 # 세션 유효 시간

spring:
  application:
    name: user
  redis:
    host: localhost # redis host
    port: 6379 # port
    password: # password, 없으면 제거
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: user
#<<< EDA / Topic Name
          destination: complain
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: complain
#>>> EDA / Topic Name
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8084
  servlet:
    session:
      cookie:
        http-only: true # 브라우저에서 해당 쿠키에 대한 JavaScript 접근을 제한합니다.
        secure: true # 쿠키가 HTTPS로 암호화된 연결에서만 쿠키가 전송됩니다.
      timeout: 3600 # 세션 유효 시간

---

spring:
  profiles: docker
  redis:
    host: localhost # redis host
    port: 6379 # port
    password: # password, 없으면 제거
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: user
          destination: complain
          contentType: application/json
        event-out:
          destination: complain
          contentType: application/json


