apiVersion: apps/v1
kind: Deployment
metadata:
  name: complaint
  labels:
    app: complaint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complaint
  template:
    metadata:
      labels:
        app: complaint
    spec:
      containers:
        - name: complaint
          image: "username/complaint:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
